CREATE TABLE "bpdrafts"
(
    "Id" UNIQUEIDENTIFIER   default newid() NOT NULL,
    "Type" NVARCHAR(10),
    "Code" NVARCHAR(20),
    "Language" INT,
    "CreatedBy" UNIQUEIDENTIFIER   default newid(),
    "UpdatedBy" UNIQUEIDENTIFIER   default newid(),
    "TaxNumberCategory" NVARCHAR(255),
    "TaxNumber" NVARCHAR(255),
    "FullVendorName" NVARCHAR(MAX),
    "Name1" NVARCHAR(MAX),
    "Name2" NVARCHAR(MAX),
    "Name3" NVARCHAR(MAX),
    "Name4" NVARCHAR(MAX),
    "SearchTearm1" NVARCHAR(255),
    "SearchTearm2" NVARCHAR(255),
    "Building" NVARCHAR(MAX),
    "HouseNo" NVARCHAR(MAX),
    "StreetName" NVARCHAR(MAX),
    "Industrialzone" NVARCHAR(MAX),
    "Ward" NVARCHAR(MAX),
    "District" NVARCHAR(MAX),
    "PostalCode" NVARCHAR(MAX),
    "City" NVARCHAR(MAX),
    "CountryKey" NVARCHAR(MAX),
    "Region" NVARCHAR(MAX),
    "FullAddress" NVARCHAR(MAX),
    "Telephone" NVARCHAR(255),
    "MobilePhone" NVARCHAR(255),
    "Fax" NVARCHAR(255),
    "Email" NVARCHAR(255),
    "LanguageCommunicate" NVARCHAR(255),
    "Comment" NVARCHAR(255),
    "BankCountryKey" NVARCHAR(255),
    "BankName" NVARCHAR(255),
    "BankBranch" NVARCHAR(255),
    "BankAddress" NVARCHAR(255),
    "Switfcode" NVARCHAR(255),
    "Iban" NVARCHAR(255),
    "AccountNumber" NVARCHAR(255),
    "AccountHoldName" NVARCHAR(255),
    "CreateProcessCode" NVARCHAR(255),
    "CompanyCode" NVARCHAR(255),
    "ReconciliationAccount" NVARCHAR(255),
    "PaymentTerm" NVARCHAR(255),
    "DoubleCheckVoice" boolean,
    "AutoPaymentTransaction" boolean,
    "AutoPaymentMethod" NVARCHAR(255),
    "HouseBank" NVARCHAR(255),
    "WithholdingTax" boolean,
    "WithholdingTaxTypeCIT" NVARCHAR(255),
    "WithholdingTaxTypeVAT" NVARCHAR(255),
    "PurchasingOrganization" NVARCHAR(255),
    "OrderCurrency" NVARCHAR(255),
    "CarrierRole" boolean,
    "CreatedAt" DATETIME,
    "UpdatedAt" DATETIME,
    CONSTRAINT "bpdrafts_uq" UNIQUE  ("Code"),
    CONSTRAINT "bpdrafts_pkey" PRIMARY KEY ("Id")
)

