CREATE TABLE "bpcustomersale"
(
    "Id" UNIQUEIDENTIFIER   default newid() NOT NULL,
    "Code" NVARCHAR(255),
    "BpId" UNIQUEIDENTIFIER   default newid(),
    "SalesOrg" NVARCHAR(255),
    "DistrChannel" NVARCHAR(255),
    "Division" NVARCHAR(255),
    "SalesDistrict" NVARCHAR(255),
    "CustomerGroup" NVARCHAR(255),
    "SalesOffice" NVARCHAR(255),
    "SalesGroup" NVARCHAR(255),
    "Currency" NVARCHAR(255),
    "ExchangeRateType" NVARCHAR(255),
    "PriceGroup" NVARCHAR(255),
    "CustPricProcedure" NVARCHAR(255),
    "DeliveryPriority" NVARCHAR(255),
    "DeliveringPlant" NVARCHAR(255),
    "ShippingConditions" NVARCHAR(255),
    "OrderCombination" boolean,
    "PODRelevant" boolean,
    "Incoterms" NVARCHAR(255),
    "IncotermsLocation1" NVARCHAR(255),
    "PaymentTerms" NVARCHAR(255),
    "AcctAssmtGrpCust" NVARCHAR(255),
    "OutputTax" NVARCHAR(255),
    "CustomerGroup2" NVARCHAR(255),
    "CustomerGroup3" NVARCHAR(255),
    "DeliveryCondition" NVARCHAR(255),
    "TruckCondition" NVARCHAR(255),
    "Zone" NVARCHAR(255),
    "EPE" NVARCHAR(255),
    "BillToParty" NVARCHAR(255),
    "Payer" NVARCHAR(255),
    "ShipToParty" NVARCHAR(255),
    "EndCustomer" NVARCHAR(255),
    "SalesEmployee" NVARCHAR(255),
    "SalesCo" NVARCHAR(255),
    "DeliveryFrom" NVARCHAR(255),
    "ContactPerson" NVARCHAR(255),
    "IsNewData" boolean,
    "SortOrder" INT,
    "CreatedAt" DATETIME,
    "UpdatedAt" DATETIME,
    "Id" UNIQUEIDENTIFIER   default newid(),
    CONSTRAINT "bpcustomersale_uq" UNIQUE  ("Code")CONSTRAINT "bpcustomersale_pkey" PRIMARY KEY ("Id")
)

